In [1]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.cluster.util import cosine_distance
from nltk import sent_tokenize,word_tokenize
import numpy as np
import re
import numpy
from numpy import delete
import math
import networkx as nx
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from gensim.models import Word2Vec
def read_article(para):
    file = open( r"C:\Users\user\vijay.txt",encoding='utf-8')
    filedata = file.read()
#     print(filedata)
    sentences = sent_tokenize(filedata)
    #print("Tokenized Sentences: ",sentences)
    sent=word_tokenize(filedata)
#     print(sentences)
    return sentences



def _create_frequency_matrix(sentences):
    frequency_matrix = {}
    stopWords = set(stopwords.words("english"))
    #ps = PorterStemmer()

    for sent in sentences:
        freq_table = {}
        words = word_tokenize(sent)
        #print(words)
        for word in words:
            word = word.lower()
            #word = ps.stem(word)
            #print(word)
            if word in stopWords:
                continue

            if word in freq_table:
                freq_table[word] += 1
            else:
                freq_table[word] = 1

        frequency_matrix[sent[:15]] = freq_table

    return frequency_matrix

def _create_tf_matrix(freq_matrix):
    tf_matrix = {}

    for sent, f_table in freq_matrix.items():
        tf_table = {}

        count_words_in_sentence = len(f_table)
        for word, count in f_table.items():
            tf_table[word] = count / count_words_in_sentence
         
        tf_matrix[sent] = tf_table

    return tf_matrix


def _create_idf_matrix(freq_matrix, count_doc_per_words, total_documents):
    idf_matrix = {}

    for sent, f_table in freq_matrix.items():
        idf_table = {}

        for word in f_table.keys():
            idf_table[word] = math.log10(total_documents / float(count_doc_per_words[word]))
            
        idf_matrix[sent] = idf_table

    return idf_matrix

def _create_documents_per_words(freq_matrix):
    word_per_doc_table = {}

    for sent, f_table in freq_matrix.items():
        for word, count in f_table.items():
            if word in word_per_doc_table:
                word_per_doc_table[word] += 1
            else:
                word_per_doc_table[word] = 1

    return word_per_doc_table

def _create_tf_idf_matrix(tf_matrix, idf_matrix):
    tf_idf_matrix = {}
    sum=0
    text=[]
    

    
    for (sent1, f_table1), (sent2, f_table2) in zip(tf_matrix.items(), idf_matrix.items()):

        tf_idf_table = {}

        for (word1, value1), (word2, value2) in zip(f_table1.items(),
                                                    f_table2.items()):  # here, keys are the same in both the table
            tf_idf_table[word1] = float(value1 * value2)
            
        
            #print(tf_idf_table[word1])
        tf_idf_matrix[sent1]= tf_idf_table
#         print(tf_idf_matrix[sent1])
        
    return tf_idf_matrix
def _tf_idf(tf_matrix, idf_matrix):
    tf_idf_matrix = {}
    sum=0
    text=[]
    

    
    for (sent1, f_table1), (sent2, f_table2) in zip(tf_matrix.items(), idf_matrix.items()):

        tf_idf_table = {}

        for (word1, value1), (word2, value2) in zip(f_table1.items(),
                                                    f_table2.items()):  # here, keys are the same in both the table
            tf_idf_table[word1] = float(value1 * value2)
            
        
            #print(tf_idf_table[word1])
            tf_idf_matrix[sent1]= tf_idf_table
#         print(tf_idf_matrix[sent1])
        s=len(tf_idf_matrix[sent1])
#         print(s)
        for i in tf_idf_matrix[sent1].values():
            
            sum=(sum+i)
            
        text.append(sum/s)
        sum=0 
    i=23  
    print(text[i])
    return text
def cosine_value(sentences):
    count_vectorizer = CountVectorizer(stop_words='english')
    count_vectorizer = CountVectorizer()
    sparse_matrix = count_vectorizer.fit_transform(sentences)


# OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
    doc_term_matrix = sparse_matrix.todense()
    df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index=[sentences])
    df
    cosine=cosine_similarity(df, df)
#     print(cosine)
    return cosine
def cal_pop_fitness(text, pop):
    n=[]
    arr=[]
    arr1=[]
    final=[]
    final1=[]
    score=[]
    file = open( r"C:\Users\user\vijay.txt",encoding='utf-8')
    filedata = file.read()
#     print(filedata)
    sentences = sent_tokenize(filedata)
    cosine=cosine_value(sentences)
    x=np.array(cosine)
    y=np.argwhere(x>0.8)
#     z=np.unique(y)

    k=0
    for i in range(len(y)): 
        if(y[i][k] ==y[i][k+1]): 
            continue

        elif(text[y[i][k]]>text[y[i][k+1]]):
            n.append(text[y[i][k]])
            arr.append(y[i][k])
            arr.append(y[i][k+1])
          
        else:
            n.append(text[y[i][k+1]])
#     print(np.unique(n))#returning the greater score
    arr1=np.unique(arr)
#     print(arr1)
#     print(y)
#     print(arr1)#returning the comparing sentences
    for i in range(len(y)):
        if (y[i][k] not in arr1):
            final.append(y[i][k])
#     print(final)#returning the other sentences
    final1=np.unique(final)
#     print(final1)
#     print(len(final1))
    for i in range(len(final1)-1):
        score.append(text[final1[i]])
#     print(score)# returning the other sentence score
    final_list=[n+score]
    final_score=np.unique(final_list)
    print("final_score  ",final_score)
    return final_score
def select_mating_pool(pop, fitness, num_parents):
    # Selecting the best individuals in the current generation as parents for producing the offspring of the next generation.
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    # The point at which crossover takes place between two parents. Usually it is at the center.
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        # Index of the first parent to mate.
        parent1_idx = k%parents.shape[0]
        # Index of the second parent to mate.
        parent2_idx = (k+1)%parents.shape[0]
        # The new offspring will have its first half of its genes taken from the first parent.
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        # The new offspring will have its second half of its genes taken from the second parent.
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover):
    # Mutation changes a single gene in each offspring randomly.
    for idx in range(offspring_crossover.shape[0]):
        # The random value to be added to the gene.
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover


def generate_summary(para, top_n=5):
    stop_words = stopwords.words('english')
    summarize_text = []

    # Step 1 - Read text anc split it
    sentences =  read_article(para)
    
    total_documents = len(sentences)
    
    freq_matrix = _create_frequency_matrix(sentences)
    #print("freqency_matrix",freq_matrix)

    
    tf_matrix = _create_tf_matrix(freq_matrix)
    #print("tf_matrix:",tf_matrix)
    count_doc_per_words = _create_documents_per_words(freq_matrix)
    
    idf_matrix = _create_idf_matrix(freq_matrix, count_doc_per_words, total_documents)
    #print("idf_matrix",idf_matrix)

    tf_idf_matrix = _create_tf_idf_matrix(tf_matrix, idf_matrix)
    #print("\n\n")
    #print("tf-idf: ",tf_idf_matrix)


    
# Create the Document Term Matrix
    
#genetic optimizer part begin
    text=_tf_idf(tf_matrix, idf_matrix)
    num_weights=6
    sol_per_pop = 30
    num_parents_mating = 2
    # Defining the population size.
    pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.
#Creating the initial population.
    new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
    print(new_population)
    num_generations = 5
    for generation in range(num_generations):
        print("Generation : ", generation)
    # Measing the fitness of each chromosome in the population.
        fitness = cal_pop_fitness(text, new_population)
        # Selecting the best parents in the population for mating.
        parents = select_mating_pool(new_population, fitness, num_parents_mating)

    # Generating next generation using crossover.
        offspring_crossover = crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    # Adding some variations to the offsrping using mutation.
        offspring_mutation = mutation(offspring_crossover)

    # Creating the new population based on the parents and offspring.
        new_population[0:parents.shape[0], :] = parents
        new_population[parents.shape[0]:, :] = offspring_mutation

    # The best result in the current iteration.
        print("Best result : ", numpy.max(fitness),fitness)#numpy.sum(new_population*text, axis=1)))

# Getting the best solution after iterating finishing all generations.
#At first, the fitness is calculated for each solution in the final generation.
#     text=_tf_idf(tf_matrix, idf_matrix)
    fitness = cal_pop_fitness(text, new_population)
# Then return the index of that solution corresponding to the best fitness.
    best_match_idx = numpy.where(fitness == numpy.max(fitness))

    print("Best solution : ", new_population[best_match_idx, :])
    print("Best solution fitness : ", fitness[best_match_idx])


generate_summary( "msft.txt", 2)
#Genetic algorithm part

0.06792992745623491
[[ 1.27472406  1.40730486  2.50479382 -1.75940996 -2.82299676 -2.40510068]
 [ 1.5730311   3.9381807  -0.13045194  1.19883806 -2.40549672  1.57571661]
 [ 2.78489456 -0.28614894 -3.59008268  2.31382869  3.74737482 -0.76078668]
 [-2.49200891 -2.0602105  -0.72792808  1.45598936  1.69251133 -0.00498203]
 [ 2.55048319  1.65645895 -3.58797945 -3.49316599 -0.36960214 -0.36210787]
 [ 0.31727294  1.76110359 -0.34144089  2.99390757  3.2674886  -0.36543652]
 [-2.19705978 -1.57342883 -0.84578744  3.74948896  3.08082378  0.64181778]
 [ 3.84327441  1.70902703 -0.56486885  1.99247607  2.4070048  -2.414635  ]
 [-3.30740751 -3.43982509  3.72474825  2.86420101 -2.4106809   3.71231301]
 [ 2.22055712  0.51065178  3.14426353 -2.23608415 -0.39063604  3.50610813]
 [-1.01599283 -3.41725283 -0.44951805  0.26064201  0.8332503  -0.77856214]
 [ 3.76154802 -2.70301631  3.34525477 -1.86292097 -3.07859787  0.17429343]
 [ 1.11915723 -3.21497171  0.17746909  1.96975205  2.83576072 -3.24887364]
 [ 0.